---
title: "Isotope reduction and report for 2018 Miller Traverse of Greenland Icesheet"
output: html_notebook
---





```{r}

library(here)
library(tidyverse)

iso_run.name = "Miller_GrIS_2018"

# Input the directory containing the raw isotope data (subdirectory of 'Raw data')
files.paths = list.files(here("Iso-runs", iso_run.name, "Raw_data/"), 
                         pattern = ".csv", full.names = TRUE)
# files.paths = choose.files(caption = "Select .csv files of raw isotope data")

# Input the .Rdata file that contains the tray template sample/standards locations
template.path = list.files(here("Iso-runs", iso_run.name, "Tray-template"), full.names = TRUE)
# template.path = choose.files(caption = 'Select Excel sample tray template file')

# Source and run the isotope reduction functions on given input files
source(here("R-functions", "iso.reduce.R"))

# Reduce isotope data
reduced.data = iso.reduce(files.paths, template.path)

```


```{r message=FALSE}

# Select only variables of interest (and only processed samples)
data = reduced.data %>% 
  filter(!str_detect(Sample_num, "^STND"), !str_detect(Sample_num, "^QC")) %>% 
  select(Sample_ID, d18O.correct, d18O.sigma, dD.correct, dD.sigma)

# Import sample locations and other field data
field.data = read_csv(here("Iso-runs", iso_run.name, "Misc", "field_data.csv"))

# Convert Sample IDs to characters and join field and iso data by Sample_ID
field.data = field.data %>% mutate(Sample_ID = as.character(Sample_ID))
data = data %>% mutate(Sample_ID = as.character(Sample_ID))
data.all = left_join(data, field.data, by = "Sample_ID")
```


```{r message=FALSE}

library(sf)
# library(gganimate)

data.sf = st_as_sf(data.all, coords = c("Lon", "Lat"), 
                   crs = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs')

plot.dD = ggplot(data.sf) + geom_sf(aes(color = dD.correct), size = 3) + scale_color_viridis_c()
plot.d18O = ggplot(data.sf) + geom_sf(aes(color = d18O.correct), size = 3) + scale_color_viridis_c()

# library(cowplot)
# p = plot_grid(plot.d18O, plot.dD, labels = "auto")

library(patchwork)
plot.dD + plot.d18O



```



```{r}

# Spatial plots of isotopes
# ggplot(data.all, aes(x = Lon, y = Lat, color = dD.correct)) + geom_point() + scale_color_viridis_c()

ggplot(data.all, aes(x = Elev, y = Temp, color = dD.correct)) + geom_point(size = 4, na.rm = TRUE) + 
  scale_color_viridis_c()

ggplot(data.all, aes(x = Temp)) + geom_point(aes(y = dD.correct), size = 3, na.rm = TRUE)

ggplot(data.all, aes(x = Temp)) + geom_point(aes(y = d18O.correct), size = 3, na.rm = TRUE)


mwl = tibble(d18O = seq(min(data.all$d18O.correct), max(data.all$d18O.correct), by = 0.1)) %>%
  mutate(dD = 8.0*d18O + 10)
ggplot(data.all, aes(x = d18O.correct, y = dD.correct)) + 
  geom_line(data = mwl, aes(x = d18O, y = dD), color = 'red', size = 2) + geom_point(color = 'black') + 
  stat_smooth(method = 'lm', size = 0.5, alpha = 0.5, color = 'black', se = FALSE) + ggtitle("Meteoric water line")

```



